// UI strings in one place so a translation can be added later (L11).
export const t = {
  brand: 'Maghanmal Jethanand',
  // Tatweel (U+0640) stretches the joins so the line runs exactly as wide as the English at 1.356em. Keep both in step.
  brandAr: 'مــغــنــمــال جــيــثــانـانـد',
  short: 'MJ Group',
  est: 'Group established 1942',
  nav: [
    { to: '/catalogue', label: 'Products' },
    { to: '/standards', label: 'Standards' },
    { to: '/#industries', label: 'Industries' },
    { to: '/founder', label: 'Our founder' },
    { to: '/since-1942', label: 'Since 1942' },
    { to: '#contact', label: 'Contact' },
  ],
  search: {
    placeholder: 'Search IPE 200, SHS 100x100',
    label: 'Search sizes',
    empty: 'No size matches. Try a shape and a size, like "SHS 100".',
  },
  quoteBtn: 'Quote',
  hero: {
    eyebrow: 'Maghanmal Jethanand Group · Since 1942',
    title: '84 years of trust. Now orderable by the row.',
    line: 'Pipes, sections, plates and more from our yards in Dubai and Sharjah. Pick the sizes. Get a quote in 2 hours.',
    browse: 'Browse products',
    start: 'Start a quote',
  },
  proof: [
    { value: '1942', label: 'Group established', count: false },
    { value: '8', label: 'Product groups', count: true },
    { value: 'SIZES', label: 'Sizes in stock', count: true },
    { value: '81', label: 'Project approvals', count: true },
    { value: '2 hr', label: 'Quote reply', count: false },
  ],
  drawn: {
    title: 'Every section, drawn to size',
    intro: 'IPE 200 as the catalogue lists it. Each icon in the range is drawn from its own row.',
    rows: [
      ['Depth', '200 mm'],
      ['Width', '100 mm'],
      ['Web', '5.6 mm'],
      ['Flange', '8.5 mm'],
      ['Root radius', '12 mm'],
      ['Mass', '22.4 kg/m'],
    ] as [string, string][],
  },
  shape: {
    title: 'Start from the shape',
    know: 'I know what I need',
    browse: "I'd like to browse",
    knowHelp: 'Type a designation. We match shape and size, with or without spaces.',
    try: 'Try',
    upload: 'Have a list ready? Upload it',
    uploadHelp: 'CSV or Excel (.xlsx) with a designation and quantity on each line. Drop it here or click to choose.',
    reading: 'Reading your list…',
    templateLink: 'Download a template',
    template: 'Designation,Quantity,Unit,Length,Grade\nSHS 100x100,24,pcs,6,S355J2H\nIPE 200,12,pcs,12,\n',
  },
  grades: {
    title: 'Grades, side by side',
    intro: 'The same steel goes by different names in European, American and Japanese standards. Match your drawing to our stock.',
    cols: ['EN 10025', 'ASTM', 'JIS', 'Yield (MPa min)'],
    link: 'Open all standards',
  },
  certs: {
    title: 'Certified and approved',
    intro: 'Paperwork that tender teams and consultants ask for, ready before you ask.',
    issuer: 'Issuer',
    number: 'Number',
    valid: 'Valid to',
  },
  founderBand: {
    label: 'Our founder',
    line: 'Be honest, helpful and friendly.',
    note: "His father's advice, as he recalled it.",
    link: 'Read his story',
  },
  steps: {
    title: 'A quote in four steps',
    items: [
      { icon: 'step-pick', title: 'Pick rows', body: 'Find the size in the table and add it to your quote.' },
      { icon: 'step-quantity', title: 'Set quantity', body: 'Pieces, metres or tonnes. We work out the weight.' },
      { icon: 'step-deliver', title: 'Tell us where', body: 'Pick the emirate, or collect from the yard.' },
      { icon: 'step-reply', title: 'We reply', body: 'A priced quote back within 2 hours in working hours.' },
    ],
  },
  industries: { title: 'Steel for the work you do', intro: 'The industries we supply every week, from single lengths to full project schedules.' },
  cta: {
    title: 'Send us your list.',
    line: 'Cut, counted and delivered from our yards in Dubai and Sharjah.',
    start: 'Start a quote',
    whatsapp: 'WhatsApp us',
    boq: 'Upload a BOQ',
  },
  catalogue: {
    title: 'Products',
    intro: 'Eight product groups, stocked in Dubai and Sharjah. Pick a group, then a size.',
    group: 'Group',
    standard: 'Standard',
    industry: 'Industry',
    all: 'All',
    viewSizes: 'View sizes',
    sizes: 'sizes',
    noMatch: 'No product family matches these filters.',
    clear: 'Clear filters',
  },
  family: {
    proof: 'Group established 1942. EN 10204 3.1 mill test certificate with every order.',
    approvals: 'On the approved-supplier list for 60 UAE projects, mostly fire-fighting pipework. Qatar 16, Saudi Arabia 5.',
    reviewed: 'Reviewed Sep 2026 · MJ technical team',
    sizeSearch: 'Find a size',
    thickness: 'Thickness',
    grade: 'Grade',
    length: 'Length',
    any: 'Any',
    cols: { designation: 'Designation', thickness: 'Thickness (mm)', mass: 'Mass (kg/m)', massM2: 'Mass (kg/m²)', width: 'Width (m)', length: 'Length (m)', qty: 'Qty (pcs)', weight: 'Theoretical weight (kg)' },
    add: 'Add to quote',
    added: 'Added',
    tabs: ['Sizes', 'Specification', 'Documents'],
    tolerances: 'Tolerances',
    grades: 'Grades',
    chemical: 'Chemical composition (% max)',
    mechanical: 'Mechanical properties',
    about: 'About this product',
    proofTitle: 'How it arrives',
    proofCaptions: ['Mill test certificate with every order', 'Colour-coded, stencilled ends', 'Strapped and packed for site'],
    noRows: 'No size matches. Clear the filters to see every size.',
  },
  rail: {
    title: 'Your quote',
    empty: 'No sizes yet. Add a row from the table and it appears here.',
    total: 'Total theoretical weight',
    review: 'Review quote',
    small: 'Need one length today? WhatsApp us.',
  },
  drawer: { title: 'Your quote', close: 'Close', review: 'Review quote', empty: 'Your quote is empty. Browse products and add a size.', browse: 'Browse products' },
  units: { pcs: 'pieces', m: 'metres', t: 'tonnes' } as const,
  stepper: ['Basket', 'Details', 'Sent'],
  quote: {
    title: 'Review your quote',
    intro: 'Check sizes and quantities. Add a grade if you know it, or leave it as "Not sure" and we will advise.',
    boq: 'Upload a BOQ, drawing or photo',
    boqHelp: 'PDF, Excel, CSV or an image. We read it and price every line.',
    boqChange: 'Replace file',
    mtc: 'Mill test certificate needed',
    notes: 'Notes',
    notesPh: "Not sure of the grade or size? Describe it here.",
    continue: 'Continue',
    continueHelp: 'Add a size, attach a file, or describe what you need in the notes.',
    notSure: 'Not sure',
    remove: 'Remove',
    empty: 'No sizes added. You can still send a BOQ or a note.',
  },
  details: {
    title: 'Where and who',
    intro: 'We need a delivery point and one way to reach you. Everything else helps us quote faster.',
    emirate: 'Delivery emirate',
    pickup: 'Pick up from yard',
    neededBy: 'Needed by',
    name: 'Your name',
    company: 'Company',
    mobile: 'Mobile or WhatsApp',
    email: 'Email',
    trn: 'TRN (optional)',
    trnHelp: 'Needed later for your tax invoice. 15 digits.',
    contactHelp: 'Give a mobile number or an email so we can send the quote.',
    send: 'Send quote request',
    sending: 'Sending your quote request',
    back: 'Back to basket',
    required: 'Required',
    errors: {
      emirate: 'Choose a delivery emirate or pick up.',
      name: 'Enter your name.',
      contact: 'Enter a mobile number or an email.',
      email: 'Enter an email like name@company.ae.',
      trn: 'A TRN has 15 digits.',
    },
  },
  received: {
    title: 'Quote request sent',
    line: 'Your reference is below. Keep it handy when we call.',
    ref: 'Reference',
    summary: 'What you asked for',
    whatsapp: 'WhatsApp this reference',
    browse: 'Browse more products',
  },
  wa: {
    title: 'Opens WhatsApp with',
    note: 'In the live site this opens WhatsApp with the message ready to send.',
    close: 'Close',
    fab: 'WhatsApp us',
    default: "Hello, I'd like a quote for steel.",
  },
  footer: {
    locations: 'Where to find us',
    contact: 'Contact',
    links: 'Explore',
    legal: '© 2026 Maghanmal Jethanand Group',
  },
  presenter: {
    items: ['Home', 'Family', 'Basket', 'Details', 'Received', 'Founder', 'Timeline'],
    fill: 'Fill basket',
    reset: 'Reset',
    marks: 'Sample marks',
    hint: 'P hides · Shift+R resets',
  },
}
