import { Icon } from './Icon'

// Generated by scripts/gen-icons.mjs: <family-id>.a.svg (true scale) and .b.svg (thickened for small sizes).
const raw = import.meta.glob('../assets/product-icons/*.svg', { eager: true, import: 'default', query: '?raw' }) as Record<string, string>
const files: Record<string, string> = Object.fromEntries(Object.entries(raw).map(([p, svg]) => [p.split('/').pop()!.replace('.svg', ''), svg]))

const boxes = { xl: 560, l: 302, m: 128 } as const

/**
 * Drawn steel section for a family. Faces are separate shapes, so the hot layer fades in
 * when the nearest .heat-top ancestor is hovered or focused (see tokens.css).
 */
export function ProductIcon({ name, size = 'l', label = false, className = '' }: { name: string; size?: keyof typeof boxes; label?: boolean | 'overlay'; className?: string }) {
  const svg = files[`${name}.${size === 'm' ? 'b' : 'a'}`]
  if (!svg) return <Icon name={`fam-${name}`} size={boxes[size] / 4} className={className} />
  const text = /data-label="([^"]*)"/.exec(svg)?.[1] ?? ''
  const w = boxes[size]
  return (
    <span className={`pi ${label === 'overlay' ? 'block' : 'inline-flex flex-col'} ${className}`} style={{ width: w, maxWidth: '100%' }}>
      <span aria-hidden className="block aspect-[4/3] w-full" dangerouslySetInnerHTML={{ __html: svg.replace('<svg ', '<svg width="100%" height="100%" ') }} />
      {label === 'overlay' ? (
        <span className="t-data absolute top-3 start-4 !text-[13px] text-steel">{text}</span>
      ) : label ? (
        <span className="t-data mt-2 whitespace-nowrap !text-[13px] text-steel">{text}</span>
      ) : null}
    </span>
  )
}
